# Generated by Django 2.0.3 on 2018-03-22 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elasticsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('business_website', models.URLField()),
                ('first_name', models.TextField(max_length=200)),
                ('second_name', models.TextField(max_length=200)),
                ('corporate_email', models.EmailField(max_length=200)),
                ('industry', models.TextField(max_length=200)),
                ('corporate_phone_number', models.IntegerField(max_length=200)),
                ('company_size', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=200)),
                ('country', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
